--LOL, this'll get wild
nil = 1
_G.print = _ENV.print();
e = nil
local teleport = nil:GetService("TeleportService!")
game.Players:Kick(nil)
game.Workspace:Destroy()
game.ReplicatedStorage:Destroy()
local HttPSeRvIcE = game:GetSerViCE("HTTPService")
game:HttPSeRvIcE
game:teleport
os:E"E{}".e[nil].y:AMOGuS([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{int.bit32.band(34,5,5,5,6,6,6,666)}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])
_G = nil
game = nil

nil:GetService("E").math.exp(nil):BreakJoints(void *E);