--LOL, this'll get wild
local nil = 1
_G.print = _ENV.print();
local e = nil
local teleport = nil:GetService("TeleportService!")
game.Players:Kick(nil)
game.Workspace:Destroy()
game.ReplicatedStorage:Destroy()
local HttPSeRvIcE = game:GetSerViCE("HTTPService")
game:HttPSeRvIcE
game:teleport
os:E"E{}".e[nil].y:AMOGuS([{([{([{([{([{([{([{([{([{([{([{([{([{([{([{}])}])}])}])}])}])}])}])}])}])}])}])}])}])}])